### ISSUE TITLE
FastAPI-NEXTAPI通信

### ISSUE THREAD

**Issue by me990928** [webfrontier-intern-20231002-20231031/todo-team-a#61]

**Comment by YokotaFumiya** [comment]
イマイチうまくいきません…
run mock serverができません…

**Comment by me990928** [comment]
@YokotaFumiya 
run mock server はどの段階の話でしょうか?
npm run dev でサーバ起動
別タブでjson-server コマンドでサーバ起動
で動くはずです

**Comment by me990928** [comment]
fastAPIをthunder-clientでget中

**Comment by me990928** [comment]
完了したので閉じます
commitはなしで
